### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by calr0x** [jheidecker/lemmony#17] opened 2023-07-08 14:03 UTC
Tried 2x and am getting this error:

calvin@SYSTEM:~/lemmony$ lemmony-cli -l $LEMMY.DOMAIN -u lemmysub -p '$PASSWORD' -t 10 -k
logging in to $LEMMY.DOMAIN as lemmysub...
fetching lemmy communities (and kbin magazines) from lemmyverse.net...
got 2353 non-empty Lemmy communities.
enumerating all locally (known) communities (this might take a while)...
done.
adding new global communities > local instance (this will take a while)...
done.
re-fetching communities ready for subscription (this might take a while)...
done.
found 1912 communities to subscribe to.
subscribing lemmysub to communities (this will take a while)...
Traceback (most recent call last):
  File "/home/calvin/.local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/calvin/.local/bin/lemmony-cli", line 8, in <module>
    sys.exit(main())
  File "/home/calvin/.local/lib/python3.10/site-packages/lemmony/cli.py", line 204, in main
    subscribe()
  File "/home/calvin/.local/lib/python3.10/site-packages/lemmony/cli.py", line 194, in subscribe
    print(str(idx) + "/" + local_community_count + " " + str(community_id) + ": " + str(sub_resp.json()['community_view']['subscribed']), end="\r")
  File "/home/calvin/.local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jheidecker** [comment] 2023-07-08 17:02
Duplicate of #2

**Comment by jheidecker** [comment] 2023-07-09 00:18
fixed in c79c01a92c281425614ec8134a0997f5d8d9b5e4

**Closed as completed by jheidecker** 2023-07-09 00:18 UTC
Labels: duplicate
